// Stock data for Blueprint Sábio
export interface Stock {
  Empresa: string;
  Código: string;
  Atuação: string;
  Lucro_líquido_estimado_2025: number;
  "P/L_projetado": number;
  "P/L_médio_10_anos": number;
  Desvio_PL: number;
  CAGR_lucros_5_anos: number;
  Dívida_líquida_EBITDA: number;
  Lucro_por_ação_estimado: number;
  Payout_esperado: number;
  Dividendo_por_ação_bruto_projetado: number;
  Dividend_Yield_bruto_estimado: number;
  Cotação_atual: number;
  Preço_Teto: number;
  Margem_de_segurança: number;
  Frequência: string;
  Meses_dividendos: string;
  Última_atualização?: string;
  Score_MSI?: number;
  PercentageToTarget?: string;
};

export const stockData: Stock[] = [
  {
    "Empresa": "Allos",
    "Código": "ALOS3",
    "Atuação": "Shoppings",
    "Lucro_líquido_estimado_2025": 1400000000,
    "P/L_projetado": 7.1,
    "P/L_médio_10_anos": 14.4,
    "Desvio_PL": -50.9,
    "CAGR_lucros_5_anos": 34.0,
    "Dívida_líquida_EBITDA": 1.90,
    "Lucro_por_ação_estimado": 2.79,
    "Payout_esperado": 50.00,
    "Dividendo_por_ação_bruto_projetado": 1.39,
    "Dividend_Yield_bruto_estimado": 7.1,
    "Cotação_atual": 19.70,
    "Preço_Teto": 23.00,
    "Margem_de_segurança": 17,
    "Frequência": "Mensal",
    "Meses_dividendos": "jan-dez",
    "Última_atualização": "18/03/2025"
  },
  {
    "Empresa": "Alupar",
    "Código": "ALUP11",
    "Atuação": "Energia",
    "Lucro_líquido_estimado_2025": 600000000,
    "P/L_projetado": 15.2,
    "P/L_médio_10_anos": 11.2,
    "Desvio_PL": 35.4,
    "CAGR_lucros_5_anos": -2.0,
    "Dívida_líquida_EBITDA": 3.50,
    "Lucro_por_ação_estimado": 1.97,
    "Payout_esperado": 50.00,
    "Dividendo_por_ação_bruto_projetado": 0.98,
    "Dividend_Yield_bruto_estimado": 3.3,
    "Cotação_atual": 29.85,
    "Preço_Teto": 25.00,
    "Margem_de_segurança": -16,
    "Frequência": "Trimestral",
    "Meses_dividendos": "abr mai ago nov",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Ambev",
    "Código": "ABEV3",
    "Atuação": "Bebidas",
    "Lucro_líquido_estimado_2025": 15000000000,
    "P/L_projetado": 14.3,
    "P/L_médio_10_anos": 22.6,
    "Desvio_PL": -36.5,
    "CAGR_lucros_5_anos": 4.8,
    "Dívida_líquida_EBITDA": -0.90,
    "Lucro_por_ação_estimado": 0.95,
    "Payout_esperado": 95.00,
    "Dividendo_por_ação_bruto_projetado": 0.91,
    "Dividend_Yield_bruto_estimado": 6.6,
    "Cotação_atual": 13.68,
    "Preço_Teto": 12.50,
    "Margem_de_segurança": -9,
    "Frequência": "Anual",
    "Meses_dividendos": "dezembro",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "B3",
    "Código": "B3SA3",
    "Atuação": "Serviços Financeiros",
    "Lucro_líquido_estimado_2025": 5000000000,
    "P/L_projetado": 13.0,
    "P/L_médio_10_anos": 21.0,
    "Desvio_PL": -38.1,
    "CAGR_lucros_5_anos": 2.0,
    "Dívida_líquida_EBITDA": -0.01,
    "Lucro_por_ação_estimado": 0.95,
    "Payout_esperado": 100.00,
    "Dividendo_por_ação_bruto_projetado": 0.95,
    "Dividend_Yield_bruto_estimado": 7.7,
    "Cotação_atual": 12.35,
    "Preço_Teto": 12.00,
    "Margem_de_segurança": -3,
    "Frequência": "Trimestral",
    "Meses_dividendos": "mar jun set dez",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Banco ABC Brasil",
    "Código": "ABCB4",
    "Atuação": "Bancos",
    "Lucro_líquido_estimado_2025": 1050000000,
    "P/L_projetado": 4.6,
    "P/L_médio_10_anos": 6.7,
    "Desvio_PL": -31.1,
    "CAGR_lucros_5_anos": 26.5,
    "Dívida_líquida_EBITDA": 0.00,
    "Lucro_por_ação_estimado": 4.43,
    "Payout_esperado": 42.00,
    "Dividendo_por_ação_bruto_projetado": 1.86,
    "Dividend_Yield_bruto_estimado": 9.1,
    "Cotação_atual": 20.45,
    "Preço_Teto": 24.37,
    "Margem_de_segurança": 19,
    "Frequência": "Semestral",
    "Meses_dividendos": "junho e dez",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Banco Banese",
    "Código": "BGIP4",
    "Atuação": "Bancos",
    "Lucro_líquido_estimado_2025": 140000000,
    "P/L_projetado": 3.4,
    "P/L_médio_10_anos": 7.3,
    "Desvio_PL": -54.0,
    "CAGR_lucros_5_anos": 22.0,
    "Dívida_líquida_EBITDA": 0.00,
    "Lucro_por_ação_estimado": 7.54,
    "Payout_esperado": 40.00,
    "Dividendo_por_ação_bruto_projetado": 3.02,
    "Dividend_Yield_bruto_estimado": 11.9,
    "Cotação_atual": 25.32,
    "Preço_Teto": 29.00,
    "Margem_de_segurança": 15,
    "Frequência": "Trimestral",
    "Meses_dividendos": "fev maio ago e nov",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Banco Banestes",
    "Código": "BEES3",
    "Atuação": "Bancos",
    "Lucro_líquido_estimado_2025": 400000000,
    "P/L_projetado": 6.5,
    "P/L_médio_10_anos": 7.2,
    "Desvio_PL": -10.3,
    "CAGR_lucros_5_anos": 10.4,
    "Dívida_líquida_EBITDA": 0.00,
    "Lucro_por_ação_estimado": 1.27,
    "Payout_esperado": 50.00,
    "Dividendo_por_ação_bruto_projetado": 0.63,
    "Dividend_Yield_bruto_estimado": 7.7,
    "Cotação_atual": 8.18,
    "Preço_Teto": 8.00,
    "Margem_de_segurança": -2,
    "Frequência": "Mensal",
    "Meses_dividendos": "jan até dez",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Banco Banrisul",
    "Código": "BRSR6",
    "Atuação": "Bancos",
    "Lucro_líquido_estimado_2025": 1000000000,
    "P/L_projetado": 4.6,
    "P/L_médio_10_anos": 6.5,
    "Desvio_PL": -30.0,
    "CAGR_lucros_5_anos": 0.0,
    "Dívida_líquida_EBITDA": 0.00,
    "Lucro_por_ação_estimado": 2.45,
    "Payout_esperado": 45.00,
    "Dividendo_por_ação_bruto_projetado": 1.10,
    "Dividend_Yield_bruto_estimado": 9.9,
    "Cotação_atual": 11.13,
    "Preço_Teto": 12.00,
    "Margem_de_segurança": 8,
    "Frequência": "Trimestral",
    "Meses_dividendos": "Mar, jun, set, dez",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Banco BMG",
    "Código": "BMGB4",
    "Atuação": "Bancos",
    "Lucro_líquido_estimado_2025": 450000000,
    "P/L_projetado": 5.0,
    "P/L_médio_10_anos": 8.3,
    "Desvio_PL": -40.2,
    "CAGR_lucros_5_anos": -2.1,
    "Dívida_líquida_EBITDA": 0.00,
    "Lucro_por_ação_estimado": 0.77,
    "Payout_esperado": 50.00,
    "Dividendo_por_ação_bruto_projetado": 0.39,
    "Dividend_Yield_bruto_estimado": 10.1,
    "Cotação_atual": 3.83,
    "Preço_Teto": 4.25,
    "Margem_de_segurança": 11,
    "Frequência": "Semestral",
    "Meses_dividendos": "abril e dezembro",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Banco Bradesco",
    "Código": "BBDC3",
    "Atuação": "Bancos",
    "Lucro_líquido_estimado_2025": 22000000000,
    "P/L_projetado": 5.5,
    "P/L_médio_10_anos": 9.3,
    "Desvio_PL": -41.2,
    "CAGR_lucros_5_anos": 1.2,
    "Dívida_líquida_EBITDA": 0.00,
    "Lucro_por_ação_estimado": 2.08,
    "Payout_esperado": 55.00,
    "Dividendo_por_ação_bruto_projetado": 1.14,
    "Dividend_Yield_bruto_estimado": 10.1,
    "Cotação_atual": 11.35,
    "Preço_Teto": 12.90,
    "Margem_de_segurança": 14,
    "Frequência": "Semestral",
    "Meses_dividendos": "junho e dez",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Banco Bradesco",
    "Código": "BBDC4",
    "Atuação": "Bancos",
    "Lucro_líquido_estimado_2025": 22000000000,
    "P/L_projetado": 6.0,
    "P/L_médio_10_anos": 10.2,
    "Desvio_PL": -41.4,
    "CAGR_lucros_5_anos": 1.2,
    "Dívida_líquida_EBITDA": 0.00,
    "Lucro_por_ação_estimado": 2.08,
    "Payout_esperado": 60.50,
    "Dividendo_por_ação_bruto_projetado": 1.26,
    "Dividend_Yield_bruto_estimado": 10.1,
    "Cotação_atual": 12.41,
    "Preço_Teto": 14.20,
    "Margem_de_segurança": 14,
    "Frequência": "Semestral",
    "Meses_dividendos": "junho e dez",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Banco da Amazônia",
    "Código": "BAZA3",
    "Atuação": "Bancos",
    "Lucro_líquido_estimado_2025": 1250000000,
    "P/L_projetado": 4.2,
    "P/L_médio_10_anos": 4.9,
    "Desvio_PL": -14.3,
    "CAGR_lucros_5_anos": 37.5,
    "Dívida_líquida_EBITDA": 0.00,
    "Lucro_por_ação_estimado": 22.30,
    "Payout_esperado": 28.00,
    "Dividendo_por_ação_bruto_projetado": 6.24,
    "Dividend_Yield_bruto_estimado": 6.7,
    "Cotação_atual": 93.69,
    "Preço_Teto": 108.00,
    "Margem_de_segurança": 15,
    "Frequência": "Anual",
    "Meses_dividendos": "abril",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Banco do Brasil",
    "Código": "BBAS3",
    "Atuação": "Bancos",
    "Lucro_líquido_estimado_2025": 39000000000,
    "P/L_projetado": 4.2,
    "P/L_médio_10_anos": 6.6,
    "Desvio_PL": -37.0,
    "CAGR_lucros_5_anos": 17.0,
    "Dívida_líquida_EBITDA": 0.00,
    "Lucro_por_ação_estimado": 6.83,
    "Payout_esperado": 36.00,
    "Dividendo_por_ação_bruto_projetado": 2.46,
    "Dividend_Yield_bruto_estimado": 8.7,
    "Cotação_atual": 28.39,
    "Preço_Teto": 34.16,
    "Margem_de_segurança": 20,
    "Frequência": "8x por ano",
    "Meses_dividendos": "fev, mai, ago, nov",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Banco Itau",
    "Código": "ITUB3",
    "Atuação": "Bancos",
    "Lucro_líquido_estimado_2025": 45000000000,
    "P/L_projetado": 6.8,
    "P/L_médio_10_anos": 9.1,
    "Desvio_PL": -24.8,
    "CAGR_lucros_5_anos": 22.8,
    "Dívida_líquida_EBITDA": 0.00,
    "Lucro_por_ação_estimado": 4.18,
    "Payout_esperado": 65.00,
    "Dividendo_por_ação_bruto_projetado": 2.72,
    "Dividend_Yield_bruto_estimado": 9.5,
    "Cotação_atual": 28.65,
    "Preço_Teto": 31.38,
    "Margem_de_segurança": 10,
    "Frequência": "Semestral",
    "Meses_dividendos": "fevereiro e ago",
    "Última_atualização": "18/03/2025"
  },
  {
    "Empresa": "Banco Itau",
    "Código": "ITUB4",
    "Atuação": "Bancos",
    "Lucro_líquido_estimado_2025": 45000000000,
    "P/L_projetado": 7.7,
    "P/L_médio_10_anos": 10.0,
    "Desvio_PL": -22.6,
    "CAGR_lucros_5_anos": 22.8,
    "Dívida_líquida_EBITDA": 0.00,
    "Lucro_por_ação_estimado": 4.18,
    "Payout_esperado": 65.00,
    "Dividendo_por_ação_bruto_projetado": 2.72,
    "Dividend_Yield_bruto_estimado": 8.4,
    "Cotação_atual": 32.38,
    "Preço_Teto": 34.52,
    "Margem_de_segurança": 7,
    "Frequência": "Semestral",
    "Meses_dividendos": "fevereiro e ago",
    "Última_atualização": "18/03/2025"
  },
  {
    "Empresa": "Banco Mercantil",
    "Código": "BMEB4",
    "Atuação": "Bancos",
    "Lucro_líquido_estimado_2025": 850000000,
    "P/L_projetado": 4.7,
    "P/L_médio_10_anos": 6.2,
    "Desvio_PL": -24.3,
    "CAGR_lucros_5_anos": 27.6,
    "Dívida_líquida_EBITDA": 0.00,
    "Lucro_por_ação_estimado": 8.11,
    "Payout_esperado": 35.00,
    "Dividendo_por_ação_bruto_projetado": 2.84,
    "Dividend_Yield_bruto_estimado": 7.5,
    "Cotação_atual": 38.08,
    "Preço_Teto": 44.60,
    "Margem_de_segurança": 17,
    "Frequência": "Semestral",
    "Meses_dividendos": "fevereiro e ago",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Banco Pine",
    "Código": "PINE4",
    "Atuação": "Bancos",
    "Lucro_líquido_estimado_2025": 230000000,
    "P/L_projetado": 4.5,
    "P/L_médio_10_anos": 7.3,
    "Desvio_PL": -38.8,
    "CAGR_lucros_5_anos": 29.9,
    "Dívida_líquida_EBITDA": 0.00,
    "Lucro_por_ação_estimado": 1.01,
    "Payout_esperado": 40.00,
    "Dividendo_por_ação_bruto_projetado": 0.40,
    "Dividend_Yield_bruto_estimado": 9.0,
    "Cotação_atual": 4.52,
    "Preço_Teto": 5.06,
    "Margem_de_segurança": 12,
    "Frequência": "Trimestral",
    "Meses_dividendos": "jan, abr, jul, out",
    "Última_atualização": "13/03/2025"
  },
  {
    "Empresa": "Banco Santander",
    "Código": "SANB4",
    "Atuação": "Bancos",
    "Lucro_líquido_estimado_2025": 15500000000,
    "P/L_projetado": 6.9,
    "P/L_médio_10_anos": 10.6,
    "Desvio_PL": -35.3,
    "CAGR_lucros_5_anos": -1.6,
    "Dívida_líquida_EBITDA": 0.00,
    "Lucro_por_ação_estimado": 2.07,
    "Payout_esperado": 55.00,
    "Dividendo_por_ação_bruto_projetado": 1.14,
    "Dividend_Yield_bruto_estimado": 8.0,
    "Cotação_atual": 14.17,
    "Preço_Teto": 15.40,
    "Margem_de_segurança": 9,
    "Frequência": "Trimestral",
    "Meses_dividendos": "fev, abr, julho e out",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Banco Santander",
    "Código": "SANB11",
    "Atuação": "Bancos",
    "Lucro_líquido_estimado_2025": 15500000000,
    "P/L_projetado": 6.5,
    "P/L_médio_10_anos": 10.6,
    "Desvio_PL": -38.5,
    "CAGR_lucros_5_anos": -1.6,
    "Dívida_líquida_EBITDA": 0.00,
    "Lucro_por_ação_estimado": 4.13,
    "Payout_esperado": 52.50,
    "Dividendo_por_ação_bruto_projetado": 2.17,
    "Dividend_Yield_bruto_estimado": 8.0,
    "Cotação_atual": 26.97,
    "Preço_Teto": 29.40,
    "Margem_de_segurança": 9,
    "Frequência": "Trimestral",
    "Meses_dividendos": "fev, abr, julho e out",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Banco Santander",
    "Código": "SANB3",
    "Atuação": "Bancos",
    "Lucro_líquido_estimado_2025": 15500000000,
    "P/L_projetado": 6.2,
    "P/L_médio_10_anos": 10.6,
    "Desvio_PL": -41.8,
    "CAGR_lucros_5_anos": -1.6,
    "Dívida_líquida_EBITDA": 0.00,
    "Lucro_por_ação_estimado": 2.07,
    "Payout_esperado": 50.00,
    "Dividendo_por_ação_bruto_projetado": 1.03,
    "Dividend_Yield_bruto_estimado": 8.1,
    "Cotação_atual": 12.75,
    "Preço_Teto": 14.00,
    "Margem_de_segurança": 10,
    "Frequência": "Trimestral",
    "Meses_dividendos": "fev, abr, julho e out",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "BB Seguridade",
    "Código": "BBSE3",
    "Atuação": "Seguros",
    "Lucro_líquido_estimado_2025": 9000000000,
    "P/L_projetado": 8.7,
    "P/L_médio_10_anos": 12.3,
    "Desvio_PL": -29.5,
    "CAGR_lucros_5_anos": 17.7,
    "Dívida_líquida_EBITDA": 0.00,
    "Lucro_por_ação_estimado": 4.64,
    "Payout_esperado": 93.37,
    "Dividendo_por_ação_bruto_projetado": 4.33,
    "Dividend_Yield_bruto_estimado": 10.8,
    "Cotação_atual": 40.23,
    "Preço_Teto": 46.36,
    "Margem_de_segurança": 15,
    "Frequência": "Semestral",
    "Meses_dividendos": "fevereiro e agosto",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "BR Partners",
    "Código": "BRBI11",
    "Atuação": "Serviços Financeiros",
    "Lucro_líquido_estimado_2025": 170000000,
    "P/L_projetado": 8.4,
    "P/L_médio_10_anos": 9.4,
    "Desvio_PL": -10.4,
    "CAGR_lucros_5_anos": 20.0,
    "Dívida_líquida_EBITDA": 0.00,
    "Lucro_por_ação_estimado": 1.62,
    "Payout_esperado": 60.00,
    "Dividendo_por_ação_bruto_projetado": 0.97,
    "Dividend_Yield_bruto_estimado": 7.1,
    "Cotação_atual": 13.63,
    "Preço_Teto": 15.38,
    "Margem_de_segurança": 13,
    "Frequência": "5x por ano",
    "Meses_dividendos": "mar abr mai ago nov",
    "Última_atualização": "18/03/2025"
  },
  {
    "Empresa": "Bradespar",
    "Código": "BRAP4",
    "Atuação": "Holding",
    "Lucro_líquido_estimado_2025": 1900000000,
    "P/L_projetado": 3.7,
    "P/L_médio_10_anos": 5.9,
    "Desvio_PL": -37.8,
    "CAGR_lucros_5_anos": 4.2,
    "Dívida_líquida_EBITDA": -0.32,
    "Lucro_por_ação_estimado": 4.83,
    "Payout_esperado": 35.00,
    "Dividendo_por_ação_bruto_projetado": 1.69,
    "Dividend_Yield_bruto_estimado": 9.5,
    "Cotação_atual": 17.74,
    "Preço_Teto": 20.00,
    "Margem_de_segurança": 13,
    "Frequência": "Semestral",
    "Meses_dividendos": "abril e novembro",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Brasilagro",
    "Código": "AGRO3",
    "Atuação": "Agronegócio",
    "Lucro_líquido_estimado_2025": 130000000,
    "P/L_projetado": 16.9,
    "P/L_médio_10_anos": 11.4,
    "Desvio_PL": 48.1,
    "CAGR_lucros_5_anos": 20.4,
    "Dívida_líquida_EBITDA": 1.86,
    "Lucro_por_ação_estimado": 1.31,
    "Payout_esperado": 65.00,
    "Dividendo_por_ação_bruto_projetado": 0.85,
    "Dividend_Yield_bruto_estimado": 3.9,
    "Cotação_atual": 22.03,
    "Preço_Teto": 23.00,
    "Margem_de_segurança": 4,
    "Frequência": "Anual",
    "Meses_dividendos": "outubro",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Caixa Seguridade",
    "Código": "CXSE3",
    "Atuação": "Seguros",
    "Lucro_líquido_estimado_2025": 4350000000,
    "P/L_projetado": 10.8,
    "P/L_médio_10_anos": 12.5,
    "Desvio_PL": -13.8,
    "CAGR_lucros_5_anos": 16.4,
    "Dívida_líquida_EBITDA": 0.00,
    "Lucro_por_ação_estimado": 1.45,
    "Payout_esperado": 90.00,
    "Dividendo_por_ação_bruto_projetado": 1.31,
    "Dividend_Yield_bruto_estimado": 8.4,
    "Cotação_atual": 15.62,
    "Preço_Teto": 15.95,
    "Margem_de_segurança": 2,
    "Frequência": "Trimestral",
    "Meses_dividendos": "jan, abr, ago e nov",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "CEB",
    "Código": "CEBR6",
    "Atuação": "Energia",
    "Lucro_líquido_estimado_2025": 190000000,
    "P/L_projetado": 7.2,
    "P/L_médio_10_anos": 7.1,
    "Desvio_PL": 0.8,
    "CAGR_lucros_5_anos": 7.3,
    "Dívida_líquida_EBITDA": -0.63,
    "Lucro_por_ação_estimado": 2.64,
    "Payout_esperado": 66.00,
    "Dividendo_por_ação_bruto_projetado": 1.74,
    "Dividend_Yield_bruto_estimado": 9.2,
    "Cotação_atual": 18.86,
    "Preço_Teto": 20.00,
    "Margem_de_segurança": 6,
    "Frequência": "Semestral",
    "Meses_dividendos": "Abril e novembro",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Cemig",
    "Código": "CMIG4",
    "Atuação": "Energia",
    "Lucro_líquido_estimado_2025": 3800000000,
    "P/L_projetado": 10.4,
    "P/L_médio_10_anos": 9.5,
    "Desvio_PL": 9.5,
    "CAGR_lucros_5_anos": 8.2,
    "Dívida_líquida_EBITDA": 1.25,
    "Lucro_por_ação_estimado": 1.86,
    "Payout_esperado": 60.00,
    "Dividendo_por_ação_bruto_projetado": 1.12,
    "Dividend_Yield_bruto_estimado": 5.9,
    "Cotação_atual": 18.95,
    "Preço_Teto": 22.32,
    "Margem_de_segurança": 18,
    "Frequência": "Semestral",
    "Meses_dividendos": "junho e dezembro",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Cesp",
    "Código": "CESP6",
    "Atuação": "Energia",
    "Lucro_líquido_estimado_2025": 650000000,
    "P/L_projetado": 11.6,
    "P/L_médio_10_anos": 10.8,
    "Desvio_PL": 7.4,
    "CAGR_lucros_5_anos": 3.5,
    "Dívida_líquida_EBITDA": 0.78,
    "Lucro_por_ação_estimado": 2.03,
    "Payout_esperado": 58.00,
    "Dividendo_por_ação_bruto_projetado": 1.18,
    "Dividend_Yield_bruto_estimado": 5.0,
    "Cotação_atual": 23.56,
    "Preço_Teto": 24.00,
    "Margem_de_segurança": 2,
    "Frequência": "Semestral",
    "Meses_dividendos": "maio e novembro",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Cosan",
    "Código": "CSAN3",
    "Atuação": "Energia",
    "Lucro_líquido_estimado_2025": 3100000000,
    "P/L_projetado": 8.5,
    "P/L_médio_10_anos": 14.7,
    "Desvio_PL": -42.2,
    "CAGR_lucros_5_anos": 10.5,
    "Dívida_líquida_EBITDA": 2.50,
    "Lucro_por_ação_estimado": 1.93,
    "Payout_esperado": 45.00,
    "Dividendo_por_ação_bruto_projetado": 0.87,
    "Dividend_Yield_bruto_estimado": 5.3,
    "Cotação_atual": 16.42,
    "Preço_Teto": 18.34,
    "Margem_de_segurança": 12,
    "Frequência": "Trimestral",
    "Meses_dividendos": "mar, jun, set, dez",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Copasa",
    "Código": "CSMG3",
    "Atuação": "Saneamento",
    "Lucro_líquido_estimado_2025": 1200000000,
    "P/L_projetado": 5.3,
    "P/L_médio_10_anos": 9.8,
    "Desvio_PL": -45.9,
    "CAGR_lucros_5_anos": 15.7,
    "Dívida_líquida_EBITDA": 1.13,
    "Lucro_por_ação_estimado": 9.53,
    "Payout_esperado": 50.00,
    "Dividendo_por_ação_bruto_projetado": 4.77,
    "Dividend_Yield_bruto_estimado": 9.5,
    "Cotação_atual": 50.21,
    "Preço_Teto": 62.00,
    "Margem_de_segurança": 23,
    "Frequência": "Semestral",
    "Meses_dividendos": "junho e dezembro",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Copel",
    "Código": "CPLE6",
    "Atuação": "Energia",
    "Lucro_líquido_estimado_2025": 3500000000,
    "P/L_projetado": 5.9,
    "P/L_médio_10_anos": 8.4,
    "Desvio_PL": -29.8,
    "CAGR_lucros_5_anos": 12.2,
    "Dívida_líquida_EBITDA": 1.05,
    "Lucro_por_ação_estimado": 1.25,
    "Payout_esperado": 65.00,
    "Dividendo_por_ação_bruto_projetado": 0.81,
    "Dividend_Yield_bruto_estimado": 10.9,
    "Cotação_atual": 7.38,
    "Preço_Teto": 9.50,
    "Margem_de_segurança": 29,
    "Frequência": "Trimestral",
    "Meses_dividendos": "mar, mai, ago, nov",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "CPFL Energia",
    "Código": "CPFE3",
    "Atuação": "Energia",
    "Lucro_líquido_estimado_2025": 5600000000,
    "P/L_projetado": 9.8,
    "P/L_médio_10_anos": 12.5,
    "Desvio_PL": -21.6,
    "CAGR_lucros_5_anos": 15.4,
    "Dívida_líquida_EBITDA": 1.45,
    "Lucro_por_ação_estimado": 4.85,
    "Payout_esperado": 75.00,
    "Dividendo_por_ação_bruto_projetado": 3.64,
    "Dividend_Yield_bruto_estimado": 7.6,
    "Cotação_atual": 47.56,
    "Preço_Teto": 48.50,
    "Margem_de_segurança": 2,
    "Frequência": "Trimestral",
    "Meses_dividendos": "mar, jun, set, dez",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "CSN",
    "Código": "CSNA3",
    "Atuação": "Siderurgia",
    "Lucro_líquido_estimado_2025": 5800000000,
    "P/L_projetado": 5.0,
    "P/L_médio_10_anos": 12.3,
    "Desvio_PL": -59.3,
    "CAGR_lucros_5_anos": 18.6,
    "Dívida_líquida_EBITDA": 2.90,
    "Lucro_por_ação_estimado": 4.20,
    "Payout_esperado": 30.00,
    "Dividendo_por_ação_bruto_projetado": 1.26,
    "Dividend_Yield_bruto_estimado": 6.0,
    "Cotação_atual": 21.00,
    "Preço_Teto": 25.20,
    "Margem_de_segurança": 20,
    "Frequência": "Anual",
    "Meses_dividendos": "maio",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "CSU Cardsystem",
    "Código": "CARD3",
    "Atuação": "Tecnologia",
    "Lucro_líquido_estimado_2025": 110000000,
    "P/L_projetado": 5.9,
    "P/L_médio_10_anos": 10.4,
    "Desvio_PL": -43.3,
    "CAGR_lucros_5_anos": 24.3,
    "Dívida_líquida_EBITDA": 0.51,
    "Lucro_por_ação_estimado": 2.65,
    "Payout_esperado": 35.00,
    "Dividendo_por_ação_bruto_projetado": 0.93,
    "Dividend_Yield_bruto_estimado": 5.9,
    "Cotação_atual": 15.65,
    "Preço_Teto": 18.55,
    "Margem_de_segurança": 19,
    "Frequência": "Trimestral",
    "Meses_dividendos": "fev, mai, ago, nov",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Cyrela",
    "Código": "CYRE3",
    "Atuação": "Construção",
    "Lucro_líquido_estimado_2025": 1100000000,
    "P/L_projetado": 8.9,
    "P/L_médio_10_anos": 11.5,
    "Desvio_PL": -22.6,
    "CAGR_lucros_5_anos": 9.8,
    "Dívida_líquida_EBITDA": -0.45,
    "Lucro_por_ação_estimado": 2.79,
    "Payout_esperado": 40.00,
    "Dividendo_por_ação_bruto_projetado": 1.12,
    "Dividend_Yield_bruto_estimado": 4.5,
    "Cotação_atual": 24.88,
    "Preço_Teto": 27.90,
    "Margem_de_segurança": 12,
    "Frequência": "Trimestral",
    "Meses_dividendos": "mar, jun, set, dez",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Duratex",
    "Código": "DTEX3",
    "Atuação": "Materiais Básicos",
    "Lucro_líquido_estimado_2025": 750000000,
    "P/L_projetado": 9.8,
    "P/L_médio_10_anos": 15.5,
    "Desvio_PL": -36.8,
    "CAGR_lucros_5_anos": 11.2,
    "Dívida_líquida_EBITDA": 1.85,
    "Lucro_por_ação_estimado": 1.08,
    "Payout_esperado": 40.00,
    "Dividendo_por_ação_bruto_projetado": 0.43,
    "Dividend_Yield_bruto_estimado": 4.1,
    "Cotação_atual": 10.59,
    "Preço_Teto": 12.42,
    "Margem_de_segurança": 17,
    "Frequência": "Trimestral",
    "Meses_dividendos": "mar, jun, set, dez",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Eletrobras",
    "Código": "ELET3",
    "Atuação": "Energia",
    "Lucro_líquido_estimado_2025": 12500000000,
    "P/L_projetado": 8.5,
    "P/L_médio_10_anos": 14.7,
    "Desvio_PL": -42.2,
    "CAGR_lucros_5_anos": 22.5,
    "Dívida_líquida_EBITDA": 1.22,
    "Lucro_por_ação_estimado": 6.62,
    "Payout_esperado": 40.00,
    "Dividendo_por_ação_bruto_projetado": 2.65,
    "Dividend_Yield_bruto_estimado": 4.7,
    "Cotação_atual": 56.18,
    "Preço_Teto": 66.20,
    "Margem_de_segurança": 18,
    "Frequência": "Semestral",
    "Meses_dividendos": "maio e dezembro",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Eletrobras",
    "Código": "ELET6",
    "Atuação": "Energia",
    "Lucro_líquido_estimado_2025": 12500000000,
    "P/L_projetado": 9.1,
    "P/L_médio_10_anos": 15.3,
    "Desvio_PL": -40.5,
    "CAGR_lucros_5_anos": 22.5,
    "Dívida_líquida_EBITDA": 1.22,
    "Lucro_por_ação_estimado": 6.62,
    "Payout_esperado": 45.00,
    "Dividendo_por_ação_bruto_projetado": 2.98,
    "Dividend_Yield_bruto_estimado": 4.9,
    "Cotação_atual": 60.42,
    "Preço_Teto": 70.00,
    "Margem_de_segurança": 16,
    "Frequência": "Semestral",
    "Meses_dividendos": "maio e dezembro",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Embraer",
    "Código": "EMBR3",
    "Atuação": "Bens de Capital",
    "Lucro_líquido_estimado_2025": 2800000000,
    "P/L_projetado": 11.7,
    "P/L_médio_10_anos": 20.3,
    "Desvio_PL": -42.4,
    "CAGR_lucros_5_anos": 24.8,
    "Dívida_líquida_EBITDA": 2.25,
    "Lucro_por_ação_estimado": 3.81,
    "Payout_esperado": 25.00,
    "Dividendo_por_ação_bruto_projetado": 0.95,
    "Dividend_Yield_bruto_estimado": 2.1,
    "Cotação_atual": 44.54,
    "Preço_Teto": 48.01,
    "Margem_de_segurança": 8,
    "Frequência": "Anual",
    "Meses_dividendos": "maio",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Energias do Brasil",
    "Código": "ENBR3",
    "Atuação": "Energia",
    "Lucro_líquido_estimado_2025": 1700000000,
    "P/L_projetado": 8.3,
    "P/L_médio_10_anos": 9.5,
    "Desvio_PL": -12.6,
    "CAGR_lucros_5_anos": 8.7,
    "Dívida_líquida_EBITDA": 1.45,
    "Lucro_por_ação_estimado": 2.84,
    "Payout_esperado": 70.00,
    "Dividendo_por_ação_bruto_projetado": 1.99,
    "Dividend_Yield_bruto_estimado": 8.4,
    "Cotação_atual": 23.55,
    "Preço_Teto": 25.56,
    "Margem_de_segurança": 9,
    "Frequência": "Semestral",
    "Meses_dividendos": "maio e outubro",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Energisa",
    "Código": "ENGI11",
    "Atuação": "Energia",
    "Lucro_líquido_estimado_2025": 2800000000,
    "P/L_projetado": 9.1,
    "P/L_médio_10_anos": 13.4,
    "Desvio_PL": -32.1,
    "CAGR_lucros_5_anos": 18.3,
    "Dívida_líquida_EBITDA": 2.64,
    "Lucro_por_ação_estimado": 5.44,
    "Payout_esperado": 50.00,
    "Dividendo_por_ação_bruto_projetado": 2.72,
    "Dividend_Yield_bruto_estimado": 5.5,
    "Cotação_atual": 49.49,
    "Preço_Teto": 54.40,
    "Margem_de_segurança": 10,
    "Frequência": "Trimestral",
    "Meses_dividendos": "mar, jun, set, dez",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Engie Brasil",
    "Código": "EGIE3",
    "Atuação": "Energia",
    "Lucro_líquido_estimado_2025": 3400000000,
    "P/L_projetado": 10.2,
    "P/L_médio_10_anos": 12.8,
    "Desvio_PL": -20.3,
    "CAGR_lucros_5_anos": 7.2,
    "Dívida_líquida_EBITDA": 2.55,
    "Lucro_por_ação_estimado": 4.17,
    "Payout_esperado": 95.00,
    "Dividendo_por_ação_bruto_projetado": 3.96,
    "Dividend_Yield_bruto_estimado": 9.3,
    "Cotação_atual": 42.53,
    "Preço_Teto": 45.87,
    "Margem_de_segurança": 8,
    "Frequência": "Trimestral",
    "Meses_dividendos": "mar, mai, ago, nov",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Equatorial",
    "Código": "EQTL3",
    "Atuação": "Energia",
    "Lucro_líquido_estimado_2025": 4800000000,
    "P/L_projetado": 11.6,
    "P/L_médio_10_anos": 14.3,
    "Desvio_PL": -18.9,
    "CAGR_lucros_5_anos": 23.5,
    "Dívida_líquida_EBITDA": 2.14,
    "Lucro_por_ação_estimado": 2.33,
    "Payout_esperado": 50.00,
    "Dividendo_por_ação_bruto_projetado": 1.16,
    "Dividend_Yield_bruto_estimado": 4.3,
    "Cotação_atual": 27.04,
    "Preço_Teto": 29.13,
    "Margem_de_segurança": 8,
    "Frequência": "Semestral",
    "Meses_dividendos": "maio e novembro",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Eztec",
    "Código": "EZTC3",
    "Atuação": "Construção",
    "Lucro_líquido_estimado_2025": 420000000,
    "P/L_projetado": 7.3,
    "P/L_médio_10_anos": 10.5,
    "Desvio_PL": -30.5,
    "CAGR_lucros_5_anos": 6.8,
    "Dívida_líquida_EBITDA": 0.10,
    "Lucro_por_ação_estimado": 2.54,
    "Payout_esperado": 40.00,
    "Dividendo_por_ação_bruto_projetado": 1.02,
    "Dividend_Yield_bruto_estimado": 5.5,
    "Cotação_atual": 18.49,
    "Preço_Teto": 22.86,
    "Margem_de_segurança": 24,
    "Frequência": "Trimestral",
    "Meses_dividendos": "jan, abr, jul, out",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Ferbasa",
    "Código": "FESA4",
    "Atuação": "Siderurgia",
    "Lucro_líquido_estimado_2025": 600000000,
    "P/L_projetado": 5.6,
    "P/L_médio_10_anos": 8.2,
    "Desvio_PL": -31.7,
    "CAGR_lucros_5_anos": 15.3,
    "Dívida_líquida_EBITDA": -0.40,
    "Lucro_por_ação_estimado": 6.62,
    "Payout_esperado": 30.00,
    "Dividendo_por_ação_bruto_projetado": 1.99,
    "Dividend_Yield_bruto_estimado": 5.4,
    "Cotação_atual": 36.88,
    "Preço_Teto": 42.41,
    "Margem_de_segurança": 15,
    "Frequência": "Trimestral",
    "Meses_dividendos": "mar, jun, set, dez",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Fleury",
    "Código": "FLRY3",
    "Atuação": "Saúde",
    "Lucro_líquido_estimado_2025": 650000000,
    "P/L_projetado": 13.2,
    "P/L_médio_10_anos": 19.8,
    "Desvio_PL": -33.3,
    "CAGR_lucros_5_anos": 12.7,
    "Dívida_líquida_EBITDA": 1.75,
    "Lucro_por_ação_estimado": 2.06,
    "Payout_esperado": 45.00,
    "Dividendo_por_ação_bruto_projetado": 0.93,
    "Dividend_Yield_bruto_estimado": 3.4,
    "Cotação_atual": 27.15,
    "Preço_Teto": 28.84,
    "Margem_de_segurança": 6,
    "Frequência": "Semestral",
    "Meses_dividendos": "abril e outubro",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Gerdau",
    "Código": "GGBR4",
    "Atuação": "Siderurgia",
    "Lucro_líquido_estimado_2025": 8500000000,
    "P/L_projetado": 7.2,
    "P/L_médio_10_anos": 11.5,
    "Desvio_PL": -37.4,
    "CAGR_lucros_5_anos": 15.8,
    "Dívida_líquida_EBITDA": 0.30,
    "Lucro_por_ação_estimado": 4.93,
    "Payout_esperado": 35.00,
    "Dividendo_por_ação_bruto_projetado": 1.73,
    "Dividend_Yield_bruto_estimado": 4.9,
    "Cotação_atual": 35.41,
    "Preço_Teto": 44.37,
    "Margem_de_segurança": 25,
    "Frequência": "Trimestral",
    "Meses_dividendos": "mar, jun, set, dez",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Hapvida",
    "Código": "HAPV3",
    "Atuação": "Saúde",
    "Lucro_líquido_estimado_2025": 1900000000,
    "P/L_projetado": 14.2,
    "P/L_médio_10_anos": 23.8,
    "Desvio_PL": -40.3,
    "CAGR_lucros_5_anos": 18.5,
    "Dívida_líquida_EBITDA": 1.85,
    "Lucro_por_ação_estimado": 0.25,
    "Payout_esperado": 25.00,
    "Dividendo_por_ação_bruto_projetado": 0.06,
    "Dividend_Yield_bruto_estimado": 1.7,
    "Cotação_atual": 3.56,
    "Preço_Teto": 4.13,
    "Margem_de_segurança": 16,
    "Frequência": "Semestral",
    "Meses_dividendos": "março e setembro",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Hypera",
    "Código": "HYPE3",
    "Atuação": "Saúde",
    "Lucro_líquido_estimado_2025": 2400000000,
    "P/L_projetado": 11.5,
    "P/L_médio_10_anos": 17.2,
    "Desvio_PL": -33.1,
    "CAGR_lucros_5_anos": 5.8,
    "Dívida_líquida_EBITDA": 1.43,
    "Lucro_por_ação_estimado": 3.79,
    "Payout_esperado": 60.00,
    "Dividendo_por_ação_bruto_projetado": 2.27,
    "Dividend_Yield_bruto_estimado": 5.2,
    "Cotação_atual": 43.58,
    "Preço_Teto": 45.48,
    "Margem_de_segurança": 4,
    "Frequência": "Semestral",
    "Meses_dividendos": "julho e janeiro",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Iguatemi",
    "Código": "IGTI11",
    "Atuação": "Shoppings",
    "Lucro_líquido_estimado_2025": 450000000,
    "P/L_projetado": 14.3,
    "P/L_médio_10_anos": 22.5,
    "Desvio_PL": -36.4,
    "CAGR_lucros_5_anos": 12.7,
    "Dívida_líquida_EBITDA": 2.10,
    "Lucro_por_ação_estimado": 2.55,
    "Payout_esperado": 50.00,
    "Dividendo_por_ação_bruto_projetado": 1.28,
    "Dividend_Yield_bruto_estimado": 3.5,
    "Cotação_atual": 36.38,
    "Preço_Teto": 38.25,
    "Margem_de_segurança": 5,
    "Frequência": "Trimestral",
    "Meses_dividendos": "mar, jun, set, dez",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "IRB Brasil",
    "Código": "IRBR3",
    "Atuação": "Seguros",
    "Lucro_líquido_estimado_2025": 650000000,
    "P/L_projetado": 5.5,
    "P/L_médio_10_anos": 12.8,
    "Desvio_PL": -57.0,
    "CAGR_lucros_5_anos": -5.8,
    "Dívida_líquida_EBITDA": 0.00,
    "Lucro_por_ação_estimado": 0.84,
    "Payout_esperado": 30.00,
    "Dividendo_por_ação_bruto_projetado": 0.25,
    "Dividend_Yield_bruto_estimado": 5.4,
    "Cotação_atual": 4.63,
    "Preço_Teto": 5.88,
    "Margem_de_segurança": 27,
    "Frequência": "Anual",
    "Meses_dividendos": "abril",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Itaúsa",
    "Código": "ITSA4",
    "Atuação": "Holding",
    "Lucro_líquido_estimado_2025": 17500000000,
    "P/L_projetado": 8.6,
    "P/L_médio_10_anos": 11.3,
    "Desvio_PL": -23.9,
    "CAGR_lucros_5_anos": 17.5,
    "Dívida_líquida_EBITDA": 0.12,
    "Lucro_por_ação_estimado": 1.16,
    "Payout_esperado": 70.00,
    "Dividendo_por_ação_bruto_projetado": 0.81,
    "Dividend_Yield_bruto_estimado": 8.1,
    "Cotação_atual": 10.00,
    "Preço_Teto": 11.60,
    "Margem_de_segurança": 16,
    "Frequência": "Mensal",
    "Meses_dividendos": "Todos os meses",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Klabin",
    "Código": "KLBN11",
    "Atuação": "Papel e Celulose",
    "Lucro_líquido_estimado_2025": 4100000000,
    "P/L_projetado": 7.5,
    "P/L_médio_10_anos": 12.8,
    "Desvio_PL": -41.4,
    "CAGR_lucros_5_anos": 22.7,
    "Dívida_líquida_EBITDA": 2.10,
    "Lucro_por_ação_estimado": 3.06,
    "Payout_esperado": 60.00,
    "Dividendo_por_ação_bruto_projetado": 1.84,
    "Dividend_Yield_bruto_estimado": 8.0,
    "Cotação_atual": 22.98,
    "Preço_Teto": 30.60,
    "Margem_de_segurança": 33,
    "Frequência": "Trimestral",
    "Meses_dividendos": "jan, abr, jul, out",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Localiza",
    "Código": "RENT3",
    "Atuação": "Locação",
    "Lucro_líquido_estimado_2025": 3800000000,
    "P/L_projetado": 15.8,
    "P/L_médio_10_anos": 28.5,
    "Desvio_PL": -44.6,
    "CAGR_lucros_5_anos": 26.3,
    "Dívida_líquida_EBITDA": 1.90,
    "Lucro_por_ação_estimado": 3.68,
    "Payout_esperado": 30.00,
    "Dividendo_por_ação_bruto_projetado": 1.10,
    "Dividend_Yield_bruto_estimado": 1.9,
    "Cotação_atual": 58.21,
    "Preço_Teto": 55.20,
    "Margem_de_segurança": -5,
    "Frequência": "Semestral",
    "Meses_dividendos": "maio e outubro",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "M. Dias Branco",
    "Código": "MDIA3",
    "Atuação": "Alimentos",
    "Lucro_líquido_estimado_2025": 950000000,
    "P/L_projetado": 8.5,
    "P/L_médio_10_anos": 15.2,
    "Desvio_PL": -44.1,
    "CAGR_lucros_5_anos": 5.3,
    "Dívida_líquida_EBITDA": 0.30,
    "Lucro_por_ação_estimado": 2.80,
    "Payout_esperado": 40.00,
    "Dividendo_por_ação_bruto_projetado": 1.12,
    "Dividend_Yield_bruto_estimado": 4.7,
    "Cotação_atual": 23.82,
    "Preço_Teto": 31.36,
    "Margem_de_segurança": 32,
    "Frequência": "Anual",
    "Meses_dividendos": "abril",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Marcopolo",
    "Código": "POMO4",
    "Atuação": "Bens de Capital",
    "Lucro_líquido_estimado_2025": 580000000,
    "P/L_projetado": 7.1,
    "P/L_médio_10_anos": 11.8,
    "Desvio_PL": -39.8,
    "CAGR_lucros_5_anos": 18.5,
    "Dívida_líquida_EBITDA": 0.12,
    "Lucro_por_ação_estimado": 0.63,
    "Payout_esperado": 45.00,
    "Dividendo_por_ação_bruto_projetado": 0.28,
    "Dividend_Yield_bruto_estimado": 6.3,
    "Cotação_atual": 4.47,
    "Preço_Teto": 5.67,
    "Margem_de_segurança": 27,
    "Frequência": "Trimestral",
    "Meses_dividendos": "fev, mai, ago, nov",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Multiplan",
    "Código": "MULT3",
    "Atuação": "Shoppings",
    "Lucro_líquido_estimado_2025": 1300000000,
    "P/L_projetado": 13.5,
    "P/L_médio_10_anos": 22.8,
    "Desvio_PL": -40.8,
    "CAGR_lucros_5_anos": 9.4,
    "Dívida_líquida_EBITDA": 1.90,
    "Lucro_por_ação_estimado": 1.38,
    "Payout_esperado": 95.00,
    "Dividendo_por_ação_bruto_projetado": 1.31,
    "Dividend_Yield_bruto_estimado": 7.0,
    "Cotação_atual": 18.64,
    "Preço_Teto": 22.08,
    "Margem_de_segurança": 18,
    "Frequência": "Trimestral",
    "Meses_dividendos": "mar, jun, set, dez",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Odontoprev",
    "Código": "ODPV3",
    "Atuação": "Saúde",
    "Lucro_líquido_estimado_2025": 350000000,
    "P/L_projetado": 10.8,
    "P/L_médio_10_anos": 18.5,
    "Desvio_PL": -41.6,
    "CAGR_lucros_5_anos": 2.8,
    "Dívida_líquida_EBITDA": -0.80,
    "Lucro_por_ação_estimado": 0.66,
    "Payout_esperado": 85.00,
    "Dividendo_por_ação_bruto_projetado": 0.56,
    "Dividend_Yield_bruto_estimado": 7.9,
    "Cotação_atual": 7.13,
    "Preço_Teto": 8.58,
    "Margem_de_segurança": 20,
    "Frequência": "Trimestral",
    "Meses_dividendos": "mar, jun, set, dez",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Omega Energia",
    "Código": "MEGA3",
    "Atuação": "Energia",
    "Lucro_líquido_estimado_2025": 650000000,
    "P/L_projetado": 13.5,
    "P/L_médio_10_anos": 18.2,
    "Desvio_PL": -25.8,
    "CAGR_lucros_5_anos": 32.5,
    "Dívida_líquida_EBITDA": 3.85,
    "Lucro_por_ação_estimado": 3.25,
    "Payout_esperado": 30.00,
    "Dividendo_por_ação_bruto_projetado": 0.98,
    "Dividend_Yield_bruto_estimado": 2.2,
    "Cotação_atual": 43.90,
    "Preço_Teto": 45.50,
    "Margem_de_segurança": 4,
    "Frequência": "Semestral",
    "Meses_dividendos": "abril e outubro",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Petrobras",
    "Código": "PETR3",
    "Atuação": "Petróleo e Gás",
    "Lucro_líquido_estimado_2025": 85000000000,
    "P/L_projetado": 6.5,
    "P/L_médio_10_anos": 9.8,
    "Desvio_PL": -33.7,
    "CAGR_lucros_5_anos": 15.0,
    "Dívida_líquida_EBITDA": 0.50,
    "Lucro_por_ação_estimado": 6.54,
    "Payout_esperado": 45.00,
    "Dividendo_por_ação_bruto_projetado": 2.94,
    "Dividend_Yield_bruto_estimado": 6.9,
    "Cotação_atual": 42.65,
    "Preço_Teto": 48.80,
    "Margem_de_segurança": 14,
    "Frequência": "Trimestral",
    "Meses_dividendos": "fev, mai, ago, nov",
    "Última_atualização": "18/03/2025"
  },
  {
    "Empresa": "Petrobras",
    "Código": "PETR4",
    "Atuação": "Petróleo e Gás",
    "Lucro_líquido_estimado_2025": 85000000000,
    "P/L_projetado": 6.1,
    "P/L_médio_10_anos": 9.3,
    "Desvio_PL": -34.4,
    "CAGR_lucros_5_anos": 15.0,
    "Dívida_líquida_EBITDA": 0.50,
    "Lucro_por_ação_estimado": 6.54,
    "Payout_esperado": 50.00,
    "Dividendo_por_ação_bruto_projetado": 3.27,
    "Dividend_Yield_bruto_estimado": 8.2,
    "Cotação_atual": 39.83,
    "Preço_Teto": 45.78,
    "Margem_de_segurança": 15,
    "Frequência": "Trimestral",
    "Meses_dividendos": "fev, mai, ago, nov",
    "Última_atualização": "18/03/2025"
  },
  {
    "Empresa": "Porto Seguro",
    "Código": "PSSA3",
    "Atuação": "Seguros",
    "Lucro_líquido_estimado_2025": 2500000000,
    "P/L_projetado": 8.5,
    "P/L_médio_10_anos": 12.3,
    "Desvio_PL": -30.9,
    "CAGR_lucros_5_anos": 11.2,
    "Dívida_líquida_EBITDA": 0.00,
    "Lucro_por_ação_estimado": 3.84,
    "Payout_esperado": 40.00,
    "Dividendo_por_ação_bruto_projetado": 1.54,
    "Dividend_Yield_bruto_estimado": 4.7,
    "Cotação_atual": 32.64,
    "Preço_Teto": 38.40,
    "Margem_de_segurança": 18,
    "Frequência": "Semestral",
    "Meses_dividendos": "junho e outubro",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Randon",
    "Código": "RAPT4",
    "Atuação": "Bens de Capital",
    "Lucro_líquido_estimado_2025": 780000000,
    "P/L_projetado": 6.7,
    "P/L_médio_10_anos": 11.2,
    "Desvio_PL": -40.2,
    "CAGR_lucros_5_anos": 13.8,
    "Dívida_líquida_EBITDA": 0.75,
    "Lucro_por_ação_estimado": 2.44,
    "Payout_esperado": 35.00,
    "Dividendo_por_ação_bruto_projetado": 0.85,
    "Dividend_Yield_bruto_estimado": 5.2,
    "Cotação_atual": 16.35,
    "Preço_Teto": 19.52,
    "Margem_de_segurança": 19,
    "Frequência": "Trimestral",
    "Meses_dividendos": "mar, jun, set, dez",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Redecard",
    "Código": "CIEL3",
    "Atuação": "Serviços Financeiros",
    "Lucro_líquido_estimado_2025": 2300000000,
    "P/L_projetado": 6.3,
    "P/L_médio_10_anos": 11.8,
    "Desvio_PL": -46.6,
    "CAGR_lucros_5_anos": 5.2,
    "Dívida_líquida_EBITDA": 0.85,
    "Lucro_por_ação_estimado": 0.85,
    "Payout_esperado": 70.00,
    "Dividendo_por_ação_bruto_projetado": 0.60,
    "Dividend_Yield_bruto_estimado": 11.3,
    "Cotação_atual": 5.33,
    "Preço_Teto": 6.80,
    "Margem_de_segurança": 28,
    "Frequência": "Trimestral",
    "Meses_dividendos": "mar, jun, set, dez",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Rumo Logística",
    "Código": "RAIL3",
    "Atuação": "Logística",
    "Lucro_líquido_estimado_2025": 2400000000,
    "P/L_projetado": 11.2,
    "P/L_médio_10_anos": 16.5,
    "Desvio_PL": -32.1,
    "CAGR_lucros_5_anos": 28.5,
    "Dívida_líquida_EBITDA": 2.40,
    "Lucro_por_ação_estimado": 1.32,
    "Payout_esperado": 25.00,
    "Dividendo_por_ação_bruto_projetado": 0.33,
    "Dividend_Yield_bruto_estimado": 2.3,
    "Cotação_atual": 14.78,
    "Preço_Teto": 17.16,
    "Margem_de_segurança": 16,
    "Frequência": "Anual",
    "Meses_dividendos": "março",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Sanepar",
    "Código": "SAPR11",
    "Atuação": "Saneamento",
    "Lucro_líquido_estimado_2025": 1650000000,
    "P/L_projetado": 5.2,
    "P/L_médio_10_anos": 8.7,
    "Desvio_PL": -40.2,
    "CAGR_lucros_5_anos": 10.8,
    "Dívida_líquida_EBITDA": 1.20,
    "Lucro_por_ação_estimado": 6.57,
    "Payout_esperado": 60.00,
    "Dividendo_por_ação_bruto_projetado": 3.94,
    "Dividend_Yield_bruto_estimado": 11.5,
    "Cotação_atual": 34.19,
    "Preço_Teto": 42.71,
    "Margem_de_segurança": 25,
    "Frequência": "Semestral",
    "Meses_dividendos": "junho e novembro",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Saraiva",
    "Código": "SLED4",
    "Atuação": "Varejo",
    "Lucro_líquido_estimado_2025": 45000000,
    "P/L_projetado": 5.2,
    "P/L_médio_10_anos": 9.8,
    "Desvio_PL": -46.9,
    "CAGR_lucros_5_anos": -8.5,
    "Dívida_líquida_EBITDA": 3.80,
    "Lucro_por_ação_estimado": 0.46,
    "Payout_esperado": 25.00,
    "Dividendo_por_ação_bruto_projetado": 0.12,
    "Dividend_Yield_bruto_estimado": 5.0,
    "Cotação_atual": 2.39,
    "Preço_Teto": 3.22,
    "Margem_de_segurança": 35,
    "Frequência": "Anual",
    "Meses_dividendos": "abril",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "SulAmérica",
    "Código": "SULA11",
    "Atuação": "Seguros",
    "Lucro_líquido_estimado_2025": 1400000000,
    "P/L_projetado": 8.9,
    "P/L_médio_10_anos": 12.5,
    "Desvio_PL": -28.8,
    "CAGR_lucros_5_anos": 8.5,
    "Dívida_líquida_EBITDA": 0.00,
    "Lucro_por_ação_estimado": 2.18,
    "Payout_esperado": 55.00,
    "Dividendo_por_ação_bruto_projetado": 1.20,
    "Dividend_Yield_bruto_estimado": 6.2,
    "Cotação_atual": 19.41,
    "Preço_Teto": 21.80,
    "Margem_de_segurança": 12,
    "Frequência": "Trimestral",
    "Meses_dividendos": "mar, jun, set, dez",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Suzano",
    "Código": "SUZB3",
    "Atuação": "Papel e Celulose",
    "Lucro_líquido_estimado_2025": 9800000000,
    "P/L_projetado": 7.3,
    "P/L_médio_10_anos": 12.8,
    "Desvio_PL": -42.9,
    "CAGR_lucros_5_anos": 25.3,
    "Dívida_líquida_EBITDA": 1.70,
    "Lucro_por_ação_estimado": 7.05,
    "Payout_esperado": 40.00,
    "Dividendo_por_ação_bruto_projetado": 2.82,
    "Dividend_Yield_bruto_estimado": 5.5,
    "Cotação_atual": 51.46,
    "Preço_Teto": 63.45,
    "Margem_de_segurança": 23,
    "Frequência": "Semestral",
    "Meses_dividendos": "janeiro e julho",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Taesa",
    "Código": "TAEE11",
    "Atuação": "Energia",
    "Lucro_líquido_estimado_2025": 1900000000,
    "P/L_projetado": 7.8,
    "P/L_médio_10_anos": 9.5,
    "Desvio_PL": -17.9,
    "CAGR_lucros_5_anos": 7.3,
    "Dívida_líquida_EBITDA": 2.30,
    "Lucro_por_ação_estimado": 5.53,
    "Payout_esperado": 90.00,
    "Dividendo_por_ação_bruto_projetado": 4.98,
    "Dividend_Yield_bruto_estimado": 11.5,
    "Cotação_atual": 43.21,
    "Preço_Teto": 47.00,
    "Margem_de_segurança": 9,
    "Frequência": "Trimestral",
    "Meses_dividendos": "fev, mai, ago, nov",
    "Última_atualização": "18/03/2025"
  },
  {
    "Empresa": "Telefônica Brasil",
    "Código": "VIVT3",
    "Atuação": "Telecomunicações",
    "Lucro_líquido_estimado_2025": 6500000000,
    "P/L_projetado": 11.2,
    "P/L_médio_10_anos": 14.8,
    "Desvio_PL": -24.3,
    "CAGR_lucros_5_anos": 8.7,
    "Dívida_líquida_EBITDA": 0.30,
    "Lucro_por_ação_estimado": 3.96,
    "Payout_esperado": 85.00,
    "Dividendo_por_ação_bruto_projetado": 3.37,
    "Dividend_Yield_bruto_estimado": 7.6,
    "Cotação_atual": 44.34,
    "Preço_Teto": 47.52,
    "Margem_de_segurança": 7,
    "Frequência": "Anual",
    "Meses_dividendos": "fevereiro",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Tim",
    "Código": "TIMS3",
    "Atuação": "Telecomunicações",
    "Lucro_líquido_estimado_2025": 4200000000,
    "P/L_projetado": 8.5,
    "P/L_médio_10_anos": 13.2,
    "Desvio_PL": -35.6,
    "CAGR_lucros_5_anos": 12.3,
    "Dívida_líquida_EBITDA": 0.45,
    "Lucro_por_ação_estimado": 1.73,
    "Payout_esperado": 75.00,
    "Dividendo_por_ação_bruto_projetado": 1.30,
    "Dividend_Yield_bruto_estimado": 8.9,
    "Cotação_atual": 14.67,
    "Preço_Teto": 17.30,
    "Margem_de_segurança": 18,
    "Frequência": "Trimestral",
    "Meses_dividendos": "jan, abr, jul, out",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Transmissão Paulista",
    "Código": "TRPL4",
    "Atuação": "Energia",
    "Lucro_líquido_estimado_2025": 3500000000,
    "P/L_projetado": 8.7,
    "P/L_médio_10_anos": 10.5,
    "Desvio_PL": -17.1,
    "CAGR_lucros_5_anos": 6.2,
    "Dívida_líquida_EBITDA": 1.10,
    "Lucro_por_ação_estimado": 5.30,
    "Payout_esperado": 70.00,
    "Dividendo_por_ação_bruto_projetado": 3.71,
    "Dividend_Yield_bruto_estimado": 8.0,
    "Cotação_atual": 46.12,
    "Preço_Teto": 47.70,
    "Margem_de_segurança": 3,
    "Frequência": "Trimestral",
    "Meses_dividendos": "fev, mai, ago, nov",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Unipar",
    "Código": "UNIP6",
    "Atuação": "Químicos",
    "Lucro_líquido_estimado_2025": 850000000,
    "P/L_projetado": 7.2,
    "P/L_médio_10_anos": 10.4,
    "Desvio_PL": -30.8,
    "CAGR_lucros_5_anos": 31.2,
    "Dívida_líquida_EBITDA": -0.30,
    "Lucro_por_ação_estimado": 8.41,
    "Payout_esperado": 40.00,
    "Dividendo_por_ação_bruto_projetado": 3.36,
    "Dividend_Yield_bruto_estimado": 5.5,
    "Cotação_atual": 61.05,
    "Preço_Teto": 75.69,
    "Margem_de_segurança": 24,
    "Frequência": "Semestral",
    "Meses_dividendos": "maio e novembro",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Usiminas",
    "Código": "USIM5",
    "Atuação": "Siderurgia",
    "Lucro_líquido_estimado_2025": 2800000000,
    "P/L_projetado": 4.3,
    "P/L_médio_10_anos": 10.8,
    "Desvio_PL": -60.2,
    "CAGR_lucros_5_anos": 12.0,
    "Dívida_líquida_EBITDA": 0.65,
    "Lucro_por_ação_estimado": 2.17,
    "Payout_esperado": 35.00,
    "Dividendo_por_ação_bruto_projetado": 0.76,
    "Dividend_Yield_bruto_estimado": 8.2,
    "Cotação_atual": 9.30,
    "Preço_Teto": 14.11,
    "Margem_de_segurança": 52,
    "Frequência": "Anual",
    "Meses_dividendos": "abril",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Vale",
    "Código": "VALE3",
    "Atuação": "Mineração",
    "Lucro_líquido_estimado_2025": 62000000000,
    "P/L_projetado": 6.8,
    "P/L_médio_10_anos": 9.8,
    "Desvio_PL": -30.6,
    "CAGR_lucros_5_anos": 5.6,
    "Dívida_líquida_EBITDA": 0.40,
    "Lucro_por_ação_estimado": 10.43,
    "Payout_esperado": 55.00,
    "Dividendo_por_ação_bruto_projetado": 5.74,
    "Dividend_Yield_bruto_estimado": 8.1,
    "Cotação_atual": 70.85,
    "Preço_Teto": 93.87,
    "Margem_de_segurança": 32,
    "Frequência": "Semestral",
    "Meses_dividendos": "março e setembro",
    "Última_atualização": "18/03/2025"
  },
  {
    "Empresa": "Via Varejo",
    "Código": "VIIA3",
    "Atuação": "Varejo",
    "Lucro_líquido_estimado_2025": 650000000,
    "P/L_projetado": 7.5,
    "P/L_médio_10_anos": 15.8,
    "Desvio_PL": -52.5,
    "CAGR_lucros_5_anos": -8.0,
    "Dívida_líquida_EBITDA": 2.80,
    "Lucro_por_ação_estimado": 0.41,
    "Payout_esperado": 30.00,
    "Dividendo_por_ação_bruto_projetado": 0.12,
    "Dividend_Yield_bruto_estimado": 3.9,
    "Cotação_atual": 3.07,
    "Preço_Teto": 4.10,
    "Margem_de_segurança": 34,
    "Frequência": "Anual",
    "Meses_dividendos": "abril",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Weg",
    "Código": "WEGE3",
    "Atuação": "Bens de Capital",
    "Lucro_líquido_estimado_2025": 5800000000,
    "P/L_projetado": 24.5,
    "P/L_médio_10_anos": 28.5,
    "Desvio_PL": -14.0,
    "CAGR_lucros_5_anos": 15.8,
    "Dívida_líquida_EBITDA": -0.75,
    "Lucro_por_ação_estimado": 1.38,
    "Payout_esperado": 40.00,
    "Dividendo_por_ação_bruto_projetado": 0.55,
    "Dividend_Yield_bruto_estimado": 1.6,
    "Cotação_atual": 33.82,
    "Preço_Teto": 29.00,
    "Margem_de_segurança": -14,
    "Frequência": "Trimestral",
    "Meses_dividendos": "mar, jun, set, dez",
    "Última_atualização": "08/03/2025"
  },
  {
    "Empresa": "Whirlpool",
    "Código": "WHRL4",
    "Atuação": "Eletrodomésticos",
    "Lucro_líquido_estimado_2025": 450000000,
    "P/L_projetado": 6.8,
    "P/L_médio_10_anos": 10.5,
    "Desvio_PL": -35.2,
    "CAGR_lucros_5_anos": 3.8,
    "Dívida_líquida_EBITDA": 0.20,
    "Lucro_por_ação_estimado": 7.26,
    "Payout_esperado": 55.00,
    "Dividendo_por_ação_bruto_projetado": 3.99,
    "Dividend_Yield_bruto_estimado": 8.1,
    "Cotação_atual": 49.37,
    "Preço_Teto": 65.34,
    "Margem_de_segurança": 32,
    "Frequência": "Anual",
    "Meses_dividendos": "maio",
    "Última_atualização": "08/03/2025"
  }
];